### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by VahidNZ** [3dash/xACARS#11] opened 2021-05-07 08:27 UTC
Hi,
I just downloaded the latest version ( Current is V1.0.0.-alpha2) I've inserted the Airline configuration and details I got the below error:

![image](https://user-images.githubusercontent.com/17470284/117421337-b2a0af00-af33-11eb-8b0e-18da390b6115.png)

Regards,
Vahid NZ

**Comment by slimit75** [comment] 2021-05-07 13:06
Good morning/afternoon! Whats the URL you put in under airline?

**Comment by slimit75** [comment] 2021-05-07 16:46
Hmm ill try and look into the issue, while I do that though can you verify that the API key you put in is typed correctly?

**Comment by VahidNZ** [comment] 2021-05-08 06:49
Yes, I copied the API key from my profile and also I try to generate a new one but the result was the same.

**Comment by hcshires** [comment] 2021-05-08 16:52
Are you using your full username from your VMS account (not the abbreviated one on your profile page)?

**Comment by VahidNZ** [comment] 2021-05-10 08:31
As far as I know, the email address is the username in this case but I try my email address and my airline id as well but the result is the same.

**Comment by slimit75** [comment] 2021-05-10 23:20
Hmm, it seems that I cant even log in because of an invalid API key...

**Comment by slimit75** [comment] 2021-05-10 23:28
I figured it out, the issue will be fixed in the next update. Here is what you can do in the meantime:
- Find airlines.ini
- Put your API key under apikey, and remove the whitespace if needed

This is caused by an issue with how it checks the credentials, frankly I don't know how I designed it this way or how I thought it would be a good idea to have it check with itself instead of the actual VA.....

**Comment by hcshires** [comment] 2021-05-11 15:26
> I figured it out, the issue will be fixed in the next update. Here is what you can do in the meantime:
> 
> * Find airlines.ini
> * Put your API key under apikey, and remove the whitespace if needed
> 
> This is caused by an issue with how it checks the credentials, frankly I don't know how I designed it this way or how I thought it would be a good idea to have it check with itself instead of the actual VA.....

However this is still happening if it is correct so thx speedlimit for finding the bug 👍🏻

**Comment by VahidNZ** [comment] 2021-05-12 07:07
As far as I know, the email address is the username in this case but I try my email address and my airline id as well but the result is the same.

> 
> 
> The username is not your email address. It is the full name associated with your airline account. You can find this by navigating to your sites `/admin/users` page and under the `Name` field
> 
> ![image](https://user-images.githubusercontent.com/25646224/117841991-221fe280-b243-11eb-8c8b-f20894abbc90.png)

Thank you for informing me, as I checked I got the invalid error again with full name as username and also I checked the whitespace  in API key but the issue is still happening.

**Comment by hcshires** [comment] 2021-05-13 15:55
Yep, so looks like the issue is what speedlimit described above.

**Comment by slimit75** [comment] 2021-05-22 14:26
So I have fixed the issue, in future versions the username wont be checked as only the API key is used for authentication and the API key is properly verified now. I will mark this issue as closed, and will be pushing an update soon with the fix.

**Closed by slimit75** 2021-05-22 14:26 UTC
Labels: bug
